festwrap/festwrap-server

backend/cmd/main.go
backend/internal/http/client/base_client.go
backend/internal/http/client/client.go
backend/internal/http/client/fake_client.go
backend/internal/http/sender/base_sender.go
backend/internal/http/sender/base_sender_test.go
backend/internal/http/sender/fake_sender.go
backend/internal/http/sender/sender.go
backend/internal/playlist/concurrent_playlist_service_test.go
backend/internal/playlist/spotify/spotify_playlist_repository.go
backend/internal/setlist/setlistfm/setlistfm_parser_test.go
backend/internal/setlist/setlistfm/setlistfm_setlist_repository.go
backend/internal/song/spotify/spotify_song_repository.go
backend/internal/song/spotify/spotify_songs_parser_test.go
backend/internal/testtools/check.go
backend/internal/testtools/io.go

Abstracts the sending of HTTP requests so we can reuse a big fraction of the code in the repositories but also facilitating repository testing (we will do this in incoming PRs).
Following the [scout rule](https://matheus.ro/2017/12/11/clean-code-boy-scout-rule/), we also improved consistency and good practises while implementing this (e.g. removing warning, standardizing auxiliar functions in test).
We first obtain a token as described in the [frontend](https://github.com/DanielMoraDC/festwrap/tree/main/frontend). Open the frontend app by typing this in the root of the project:
```
cd frontend
make run-app
```
Then go to [localhost](http://localhost:3000) and login in Spotify:
Once logged, you will be able to copy the token for the next step:
Then, we can run the main script to check it …

refactor: abstract http client

---

backend/cmd/main.go
backend/internal/song/songs_parser.go
backend/internal/song/spotify/fake_songs_parser.go
backend/internal/song/spotify/songs_parser.go
backend/internal/song/spotify/spotify_song_repository.go
backend/internal/song/spotify/spotify_song_repository_test.go
backend/internal/song/spotify/spotify_songs_parser.go
backend/internal/song/spotify/spotify_songs_parser_test.go

Adds tests to the Spotify song repository.
Added some additonal minor changes:
- Move interface to more suited submodule.
- Return value instead of pointer in song parser.
- Use production parser by default, enabling to change it with a setter to ease testing.

chore: test spotify song repo

---

backend/cmd/main.go
backend/internal/setlist/setlistfm/setlistfm_setlist_repository.go

In a past refactor, we enabled the default minimum songs for a valid setlist to be. As a consequence, we were always using the first setlist found, even if it was empty.
These changes consider a valid setlist to at least have one song and also fix the main backend script to actually use the provided minimum amount of songs.

fix: Use at least one songs in setlists

---

README.md

We are moving from Trello to private JIRA cloud, removing the link to old Trello.

docs: remove Trello link from README

---

backend/internal/artist/artist.go
backend/internal/artist/errors/cannot_retrieve_artists_error.go
backend/internal/artist/errors/no_image_found_error.go
backend/internal/artist/spotify/spotify_artist_deserializer.go
backend/internal/artist/spotify/spotify_artist_repository.go
backend/internal/http/client/base_client.go
backend/internal/http/client/fake_client.go
backend/internal/http/sender/base_sender.go
backend/internal/http/sender/sender.go
backend/internal/playlist/concurrent_playlist_service.go
backend/internal/playlist/errors/cannot_add_songs_to_playlist_error.go
backend/internal/playlist/errors/cannot_create_playlist_error.go
backend/internal/playlist/fake_playlist_repository.go
backend/internal/playlist/spotify/spotify_playlist_repository.go
backend/internal/serialization/errors/deserialization_error.go
backend/internal/serialization/errors/serialization_error.go
backend/internal/setlist/errors/cannot_retrieve_setlist_error.go
backend/internal/setlist/fake_setlist_repository.go
backend/internal/setlist/setlist.go
backend/internal/setlist/setlist_song.go
backend/internal/setlist/setlistfm/setlistfm_deserializer.go
backend/internal/setlist/setlistfm/setlistfm_setlist_repository.go
backend/internal/song/errors/cannot_retrieve_song_error.go
backend/internal/song/fake_song_repository.go
backend/internal/song/song.go
backend/internal/song/spotify/spotify_song_repository.go
backend/internal/song/spotify/spotify_songs_deserializer.go
backend/internal/testtools/io.go

I have not found any Golang standard for this, but I find convenient to have constructors at top, so they are more accessible when reading the code.

refactor: move constructors after definition

---

backend/cmd/middleware/auth_token.go
backend/cmd/middleware/auth_token_test.go
backend/internal/types.go

Adds a middleware that reads the bearer token and adds it to the request context. We will use this middleware for all endpoints we are going to implement, as they will require a bearer token for authenticating with the Spotify API.

feat: FW-19 Implement auth token parse middleware

---

backend/cmd/artist/search_artist.go
backend/cmd/handler/artists.go
backend/cmd/handler/artists_test.go
backend/internal/artist/artist.go
backend/internal/artist/artist_repository.go
backend/internal/artist/fake_artist_repository.go
backend/internal/artist/spotify/spotify_artist_repository.go
backend/internal/artist/spotify/spotify_artist_repository_test.go
backend/internal/serialization/encoder.go
backend/internal/serialization/fake_encoder.go

Implements handler to retrieve artists by name. It required implementing a couple of extra classes (i.e. fake repository, encoders) and modifying the repository interface to include the context. By adding the access token in the context, we do not need to couple the repository interface to the specific Spotify bearer authorization.

feat: FW-19 Implement search artist handler

---

.dockerignore
.github/workflows/push.yml
.github/workflows/release.yml
.github/workflows/tests.yml
.releaserc
Dockerfile
Makefile
cmd/handler/artists.go

These changes introduce a couple of new workflows:
- A workflow to generate a release on each merge to main.
- A workflow to push a Docker image into the Github repository on release.
Therefore, every time we merge into main, a new release and Docker image will be generated.
Also testing the Docker image can be built on each PR and merge to main.

feat: FW-20 Push docker image on release

---

.github/workflows/push.yml
.github/workflows/release.yml

Github prevents a workflow from triggering another workflow, as described here: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/triggering-a-workflow#triggering-a-workflow-from-a-workflows
Therefore, we decide to use a Github token in order to perfrom the release, so the release workflow can then trigger the workflow triggering the Docker push.
We did not include all the steps in a single job since it was not straightforward to get the semantic release value in a consistent way.
We are also fixing the tag for the docker push.

ci: FW-20 Fix release & push CI

---

.github/workflows/create-release.yml

Github workflows that use the provided GITHUB_TOKEN cannot trigger other workflows. However, workflows that run on `workflow_dispatch` are an exception to that. Therefore, we can stop using our own Personal Token here and resort to using the one provided by Github, which is more secure and maintainable.
See the [docs](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/triggering-a-workflow#triggering-a-workflow-from-a-workflow).

chore(ci): do not use personal token in flow

---

.github/workflows/push-image.yml

Starts pushing into Google Artifact Registry instead of pushing to the Github Container Registry. Removing attestation step, as I was having issues intregrating it with Google cloud.

feat(ci): push image into GCR

---

cmd/handler/artists.go
cmd/handler/artists_test.go
cmd/main.go
internal/logging/base.go
internal/logging/logger.go
internal/logging/noop.go

Add logging module and use logging in artists handler.
Start the app:
```shell
go run cmd/main.go
```
Then query the endpoint (need to generate an access token, see [here](https://github.com/DanielMoraDC/festwrap-ui)):
```shell
curl --location 'http://localhost:8080/artists/search?name=Brutus' \
--header 'Authorization: <token>'
```
We get:
```json
{"time":"2024-11-06T09:11:24.158418+01:00","level":"INFO","msg":"Received new request for Brutus, using limit 5"}
{"time":"2024-11-06T09:11:24.334223+01:00","level":"INFO","msg":"Found artist [{Brutus https://i.scdn.co/image/ab6761610000f17883678eabacd66cedd7063cf7} {Brutus' Daughters https://i.scdn.co/image/ab6761610000f178f0143378468e166f4274e1fc} {Big Brutus https://i.scdn.co/image/ab6761610000f178600cb5fcc42a845413920957} {Brutus Backlash } …
```

feat: FW-43 Add logging to handler

---

cmd/scripts/add_songs_to_playlist.go
internal/artist/spotify/spotify_artist_repository_test.go
internal/playlist/concurrent_playlist_service.go
internal/playlist/concurrent_playlist_service_test.go
internal/playlist/errors/cannot_search_playlist.go
internal/playlist/fake_playlist_repository.go
internal/playlist/playlist_repository.go
internal/playlist/playlist_service.go
internal/playlist/spotify/spotify_get_playlist_response.go
internal/playlist/spotify/spotify_playlist_repository.go
internal/playlist/spotify/spotify_playlist_repository_test.go
internal/serialization/fake_deserializer.go
internal/setlist/setlistfm/setlistfm_setlist_repository_test.go
internal/song/spotify/spotify_song_repository_test.go

Adds search playlist method in interface and creates an implementation for the Spotify repository. We are only retrieving the playlists actually owned by the user, as Spotify search returns all possible matches. User playlists, though, are always placed first.
In order to use the user id and the token inside the repository, we use the Golang context as already done in other repositories.
We also take the chance to do some scouting and reduce test boilerplate code.

feat: FW-6 iImplement playlist search in repository

---

cmd/main.go
cmd/middleware/auth_token_test.go
cmd/middleware/user_id.go
cmd/middleware/user_id_test.go
internal/playlist/spotify/spotify_playlist_repository.go
internal/playlist/spotify/spotify_playlist_repository_test.go
internal/user/fake_user_repository.go
internal/user/spotify/spotify_user_repository.go
internal/user/spotify/spotify_user_repository_test.go
internal/user/spotify/spotify_user_response.go
internal/user/user_repository.go

Adds the playlist search endpoint into the service. Spotify returns all playlists, not only the ones owned by the user. However, I observed that user owned playlists are always placed first. In order to filter those playlists, I added a middleware that extracts the current user id and places it into the Context. Then, in the repository, we can filter out the playlists whose owner do not match the current user.
Note that for simplicity we are not paginating the search results. This makes sense, for now, in the current use case.
If we locally request a playlist, we see we obtain proper results. First, starrt the app locally:
```shell
go run cmd/main.go
```
Then, in a separate terminal, type:
```
curl --location 'http://localhost:8080/playlists/search?name=Jera&limit=5' \
--header …
```

feat: FW-6 Implement playlist search endpoint

---

Makefile
README.md

Adds commands to run and stop the containerized server and documents it in the README.

docs: add instructions to run container

---

internal/playlist/concurrent_playlist_service.go
internal/playlist/concurrent_playlist_service_test.go
internal/playlist/fake_playlist_repository.go
internal/playlist/playlist_repository.go
internal/playlist/playlist_service.go
internal/playlist/spotify/spotify_playlist_repository.go
internal/playlist/spotify/spotify_playlist_repository_test.go

Adds the create playlist functionality to the playlist service, which wraps the repository.
Moreover, standardizes playlist repository to use user id from context so it is consistent with other repositories in the code base.

chore: FW-66 Implement create in service

---

cmd/handler/search/search_test.go
cmd/middleware/auth_token_test.go
cmd/middleware/user_id_test.go
go.mod
go.sum
internal/artist/spotify/spotify_artist_repository_test.go
internal/env/env_test.go
internal/http/sender/base_sender_test.go
internal/playlist/concurrent_playlist_service_test.go
internal/playlist/spotify/spotify_playlist_repository_test.go
internal/serialization/json_deserializer_test.go
internal/serialization/json_serializer_test.go
internal/setlist/setlistfm/setlistfm_setlist_repository_test.go
internal/song/spotify/spotify_song_repository_test.go
internal/testtools/check.go
internal/user/spotify/spotify_user_repository_test.go

Using `testify` dependency for asserts in tests. I initially tried to use a minimal amount of dependencies, but given that test code is becoming larger and more difficult to maintain, I decided to use a third party library.
This PR replaces the custom asserts by the `testify` ones.
We will create a separate PR to simplify fake objects by using `testify` mock.

chore: FW-72 use testify dependency for tests

---

cmd/handler/playlist/playlist_update.go
cmd/handler/playlist/update_playlist.go
cmd/handler/playlist/update_playlist_test.go
cmd/main.go
cmd/scripts/add_songs_to_playlist.go
go.mod
go.sum
internal/playlist/concurrent_playlist_service.go
internal/playlist/concurrent_playlist_service_test.go
internal/playlist/mocks/playlist_service_mock.go
internal/song/fake_song_repository.go
internal/song/song_repository.go
internal/song/spotify/spotify_song_repository.go
internal/song/spotify/spotify_song_repository_test.go

Adds an endpoint that adds the most recent setlist from the input artist to the given playlist.
Start the app locally and make sure to provide the setlistFM api token:
```shell
FESTWRAP_SETLISTFM_APIKEY=XXX go run cmd/main.go
```
I created a custom playlist in Spotify to test this:
Then we query the endpoint in a separate terminal:
```shell
curl --location 'http://localhost:8080/playlists/<playlistId>' \
--header 'Authorization: Bearer <token>' \
--header 'Content-Type: application/json' \
--data '{"artists":[{"name": "Silverstein"},{"name":"toe"}]}'
```
Note that:
- You can get a personal token using the [festwrap ui](https://github.com/DanielMoraDC/festwrap-ui).
- You can get the playlist id by selecting using the playlist link (`Share` -> `Copy playlist link`). The format will be …

feat: FW-66 Implement add songs endpoint

---

cmd/handler/playlist/playlist_update.go
cmd/handler/playlist/update_playlist.go
cmd/handler/playlist/update_playlist_test.go

Returns bad request status if no artists are provided on playlist update handler.

chore: return validation error on no artists

---

cmd/handler/playlist/playlist_update.go
cmd/handler/playlist/update_playlist.go
cmd/handler/playlist/update_playlist_test.go
cmd/main.go
internal/playlist/mocks/playlist_update_builder_mock.go
internal/playlist/playlist_update.go
internal/playlist/playlist_update_builder.go
internal/playlist/playlist_update_builder_test.go

Abstract update playlist detail extraction in order to reuse the main handler logic. We will use it for implementing the endpoint to create and add artists into the newly created playlist.

refactor: abstract update playlist builder in handler

---

cmd/handler/playlist/update_playlist.go
cmd/handler/playlist/update_playlist_test.go
cmd/main.go
internal/playlist/update_builders/playlist_update_builders.go
internal/playlist/update_builders/playlist_update_builders_test.go
internal/playlist/update_builders/updates.go

Adds a new endpoint that allows to add songs for a new playlist. I favoured duplicating small amounts of code (e.g. test and body deserialization) over creating additional abstractions that might add too much complexity to the codebase.
Start the API by typing:
```shell
FESTWRAP_SETLISTFM_APIKEY=<key>go run cmd/main.go
```
Then query the endpoint:
```shell
curl --location 'http://localhost:8080/playlists' \
--header 'Authorization: Bearer <token>' \
--header 'Content-Type: application/json' \
--data '{"artists":[{"name": "Trophy Eyes"}],"playlist":{"name":"test1","description":"","isPublic":false}}'
```
Token can be manually obtained from [here](https://github.com/DanielMoraDC/festwrap-ui). We can see that it creates the following playlist:

feat: FW-66 Implement add songs to new playlist endpoint

---

internal/playlist/concurrent_playlist_service_test.go
internal/playlist/playlist.go
internal/playlist/spotify/spotify_get_playlist_response.go
internal/playlist/spotify/spotify_playlist_repository.go
internal/playlist/spotify/spotify_playlist_repository_test.go

Includes the playlist id in search response. Additionally, refcatored a bit the playlust repository tests for better understandability.
Querying the API with the following query:
```shell
curl --location 'http://localhost:8080/playlists/search?name="emo"' \
--header 'Authorization: Bearer <token>'
```
Returns the playlists with their ids:
```json
[
{"id":"2onMcDTfKGztYIp0VJOeEP","name":"Emo rules","description":"","isPublic":true}, 
{"id":"0CEMLiTZhAqxAXQZYwgfl2","name":"Emo 90s/2000s","description":"","isPublic":true}
]
```

fix: FW-80 Return playlist id on search

---

cmd/main.go
internal/http/sender/mocks/sender_mock.go
internal/setlist/setlistfm/setlistfm_setlist_repository.go
internal/setlist/setlistfm/setlistfm_setlist_repository_test.go
internal/setlist/testdata/no_setlists_response.json

If a setlist is not found in first page, searches up to `n` pages for a result. Fails otherwise.
I also stopped replacing the deserializer dependency. Given it is not a slow one or a shared/out-of-process one, by keeping it in the test we make tests less coupled to the implementation and simpler to implement and extend. Therefore, we have moved the existing integration tests in that test suite into unit tests.
Additional minor changes:
- Use mocks for HTTP sender instead of fake in order to simplify test code and ease maintainability.
- Use simpler and concise naming in tests.
Successfully reproduced test in [here](https://github.com/DanielMoraDC/festwrap-server/pull/49).

fix: FW-9 Use SetlistFM multiple pages in search

---

cmd/handler/playlist/update_playlist_test.go
cmd/handler/search/search_test.go
cmd/middleware/auth_token_test.go
cmd/middleware/user_id_test.go
internal/artist/spotify/spotify_artist_repository_test.go
internal/env/env_test.go
internal/http/sender/base_sender_test.go
internal/playlist/concurrent_playlist_service_test.go
internal/playlist/spotify/spotify_playlist_repository_test.go
internal/playlist/update_builders/playlist_update_builders_test.go
internal/serialization/json_deserializer_test.go
internal/serialization/json_serializer_test.go
internal/setlist/setlistfm/setlistfm_setlist_repository_test.go
internal/song/spotify/spotify_song_repository_test.go
internal/user/spotify/spotify_user_repository_test.go

Changes order of asserts so they are consistent within the project and with Testify.

chore(tests): use consistent assert order

---

cmd/handler/playlist/update_playlist.go
cmd/handler/playlist/update_playlist_test.go

Returns playlist information (i.e. id) on creation. Also took the chance to return 201 status (created) only when a new playlist is created.
```shell
❯ curl --location 'http://localhost:8080/playlists/25Fqk8HMi0LppHQliZx6ta' \
--header 'Authorization: Bearer <token>' \
--header 'Content-Type: application/json' \
--data '{"artists":[{"name": "Stick to your guns"}]}' -v
* Host localhost:8080 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:8080...
* Connected to localhost (::1) port 8080
> POST /playlists/25Fqk8HMi0LppHQliZx6ta HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/8.7.1
> Accept: */*
> Authorization: Bearer <token>
> Content-Type: application/json
> Content-Length: 44
> 
* upload completely sent off: 44 bytes
< HTTP/1.1 200 OK
< Date: Mon, 31 Mar 2025 07:42:14 GMT …
```

feat: FW-88 return playlist id on create

---

README.md
internal/playlist/spotify/spotify_playlist.go
internal/playlist/spotify/spotify_playlist_repository_test.go

Fixes the `public` payload attribute. See [API docs](https://developer.spotify.com/documentation/web-api/reference/create-playlist) for more information.
Also adds a disclaimer on how to properly interpret the `isPublic` option in our endpoint, as it can be a source of confusion. We are planning a task to change the API naming to reflect the actual behavior.

fix: fix create playlist payload

---

cmd/handler/playlist/update_playlist.go
cmd/main.go

Setlistfm API has a low rate limit (2 req/s). To avoid easily hitting the limit, we are adding a delay between setlists. By doing so, we force pairs of consecutive requests to happen in separate seconds.
We are also reading the maximum amout of artists for playlist updates from the environment variables.

chore: FW-97 Add restrictions to mitigate rate limit impact

---

README.md
cmd/config.go
cmd/main.go
cmd/middleware/auth_token.go
cmd/middleware/auth_token_test.go
cmd/middleware/user_id.go
cmd/middleware/user_id_test.go
go.mod
go.sum
internal/playlist/update_builders/playlist_update_builders.go
internal/playlist/update_builders/playlist_update_builders_test.go

Restricts entrypoints to the expected specific HTTP methods. Returns 405 otherwise.
Took the chance to introduce small scouting, to help cleaning the main script.
We start the application:
```shell
FESTWRAP_SETLISTFM_APIKEY="abcde" go run ./cm
```
Then we query:
```
curl "http://localhost:8080/artists/search?name=Iron" -vvv
* Host localhost:8080 was resolved.
* IPv6: ::1
* IPv4: *********
*   Trying [::1]:8080...
* Connected to localhost (::1) port 8080
> GET /artists/search?name=Iron HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/8.7.1
> Accept: */*
> 
* Request completely sent off
< HTTP/1.1 400 Bad Request
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Wed, 21 May 2025 07:28:46 GMT
< Content-Length: 29
< 
Missing authorization header
* …
```

chore: FW-76 Restrict http methods

---

Dockerfile
README.md

The old startup command did not include other files that could be needed by the main entrypoint (i.e. `config.go`).

fix: FW-119 fix startup error
